#!/usr/bin/env node

Highlights = require('highlights')
const fs = require("fs");
const highlighter = new Highlights();

highlighter.requireGrammarsSync({ modulePath: require.resolve('language-greyscript/package.json') })

var code = fs.readFileSync(process.argv[2]).toString()

var html = highlighter.highlightSync({ fileContents: code, scopeName: 'greyscript' })

console.log(html)
