# == Schema Information
#
# Table name: invites
#
#  id            :bigint           not null, primary key
#  accepted_date :date
#  key           :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  guild_id      :bigint           not null
#  user_id       :bigint           not null
#
# Indexes
#
#  index_invites_on_guild_id  (guild_id)
#  index_invites_on_key       (key) UNIQUE
#  index_invites_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (guild_id => guilds.id)
#  fk_rails_...  (user_id => users.id)
#
require "test_helper"

class InviteTest < ActiveSupport::TestCase
  setup do
    @invite = build :invite
  end

  test "should be invalid without a key of len 32" do
    @invite.key = "a" * 31
    @invite.valid?
    refute_empty @invite.errors[:key]
    @invite.key = "a" * 33
    @invite.valid?
    refute_empty @invite.errors[:key]
    @invite.key = "a" * 32
    @invite.valid?
    assert_empty @invite.errors[:key]
  end

  test "should be invalid without a unique key" do
    @invite.save
    invite2 = build :invite, key: @invite.key
    invite2.valid?
    refute_empty invite2.errors[:key]
  end

  test "should be valid with akey generated by #set_random_key" do
    @invite.set_random_key
    @invite.valid?
    assert_empty @invite.errors[:key]
  end
end
